; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = thesun_attiny1616

[env:thesun_attiny1616]
platform = atmelmegaavr
board = ATtiny1616
framework = arduino

; Use megaTinyCore as Arduino core for tinyAVR 0/1/2-series
platform_packages =
  platformio/framework-arduino-megaavr-megatinycore@~2.6.7

build_flags =
  -DTCA_PORTMUX=PORTMUX_TCA02_bm
  -DPWMmux=I6_A

; 16 MHz internal clock (same as in Arduino Boards menu)
board_build.f_cpu = 16000000L
board_hardware.oscillator = internal

; Hardware options matching your Arduino IDE screenshot
board_hardware.bod    = 1.8v    ; Brown-Out at 1.8 V
board_hardware.eesave = yes     ; Keep EEPROM on programming
board_hardware.rstpin = updi    ; UPDI pin used as UPDI (no reset)

; --- Upload via SerialUPDI + CH340 ---
upload_protocol = serialupdi
upload_speed    = 230400        ; if unstable, try 115200

; Adjust this to your actual CH340 device name
upload_port = /dev/ttyUSB0

; --- Libraries used by your firmware ---
lib_deps =
  greiman/SSD1306Ascii
  adafruit/Adafruit AHTX0
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit BusIO

; Optional: serial monitor baud rate (if you ever use UART)
monitor_speed = 9600

extra_scripts = pre:extra_clangdb.py

[env:set_fuses]
platform = ${env:thesun_attiny1616.platform}
board    = ${env:thesun_attiny1616.board}
framework = ${env:thesun_attiny1616.framework}
platform_packages = ${env:thesun_attiny1616.platform_packages}

board_build.f_cpu = ${env:thesun_attiny1616.board_build.f_cpu}
board_hardware.oscillator = ${env:thesun_attiny1616.board_hardware.oscillator}
board_hardware.bod    = ${env:thesun_attiny1616.board_hardware.bod}
board_hardware.eesave = ${env:thesun_attiny1616.board_hardware.eesave}
board_hardware.rstpin = ${env:thesun_attiny1616.board_hardware.rstpin}

upload_protocol = ${env:thesun_attiny1616.upload_protocol}
upload_speed    = ${env:thesun_attiny1616.upload_speed}
upload_port     = ${env:thesun_attiny1616.upload_port}
